$primary = rgb(b58900)
$surface = rgb(002b36)
$secondary = rgb(d33682)
$error = rgb(dc322f)
$tertiary = rgb(cb4b16)
$surface_lowest = rgb(012d38)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
