# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

# never put virtualbox,mlocate in this list

{
  environment.systemPackages = with pkgs; [
    #ckb-next
    google-chrome
    #wpsoffice
    libreoffice
    alacritty
    arandr
    arc-theme
    avahi
    brave
    baobab
    bash-completion
    bat
    bibata-cursors
    blueberry
    btop
    gavin-bc
    chromium
    curl
    gvfs
    clipgrab
    dex
    discord
    dmenu
    dwm
    dropbox
    duf
    eza
    edid-decode
    etcher
    evince
    feh
    filezilla
    firefox
    flameshot
    font-manager
    fsearch
    gimp
    glaxnimate
    git
    gnome.dconf-editor
    gnome.gnome-disk-utility
    gnome.gvfs
    gparted
    hack-font
    hblock
    htop
    hw-probe
    hwinfo
    i3lock-fancy
    inkscape
    insync
    inxi
    killall
    kitty
    keepassxc
    lm_sensors
    lollypop
    lsd
    lshw
    libadwaita
    meld
    most
    nwg-look
    neofetch
    wayfire
    wayfirePlugins.wcm
    networkmanagerapplet
    nixos-generators
    libnotify
    nomacs
    neovim
    numlockx
    obs-studio
    ookla-speedtest
    qbittorrent-qt5
    platinum-searcher
    polybar
    qt6Packages.qtstyleplugin-kvantum
    libsForQt5.qt5ct
    qt6Packages.qt6ct
    ripgrep
    gcc
	  gh
    gnumake
    ninja
    rxvt-unicode
    scrot
    simplescreenrecorder
    spotify
    sublime4
    telegram-desktop
    tree
    variety
    #vivaldi
    #vivaldi-ffmpeg-codecs
    vlc
    vscode
    gzip
    p7zip
    peazip
    unrar
    unzip
    kdenlive
    glaxnimate
    jq
    wget
    widevine-cdm
    xorg.xkill
    yakuake
    zsh
    zsh-completions
    zsh-syntax-highlighting
    hypnotix
    
    ];
}
